#!/usr/bin/env node
// Regenerates every generated file from grammars/ and js/src/, or, with
// --check, fails if any of them is out of date:
//
//   grammars/compiled.json   the DOM of every grammar document, keyed by hash
//   js/grammars/             the npm package's copy of grammars/
//   dist/grammars.js         grammars/ as one object, for the browser
//   dist/gencmu.js           the library as one factory function, for the browser
//
// and the other packages' copies of grammars/ once they exist. No
// dependencies; run it after editing a grammar.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loaderFromDirectory, fnv1a64 } from "../js/src/node.js";
import { DOM_FORMAT } from "../js/src/dialect.js";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const grammars = path.join(root, "grammars");
const check = process.argv.includes("--check");
const stale = [];

function write(relative, content) {
  const file = path.join(root, relative);
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (current === content) return;
  stale.push(relative);
  if (!check) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
}

function grammarFiles(directory = grammars, prefix = "") {
  const files = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    const relative = prefix + entry.name;
    if (entry.isDirectory()) files.push(...grammarFiles(path.join(directory, entry.name), relative + "/"));
    else if (relative !== "compiled.json") files.push(relative);
  }
  return files;
}

// The precompiled DOMs, read with the engine and the current bootstrap.
const loader = loaderFromDirectory(grammars);
const documents = {};
for (const file of grammarFiles()) {
  if (!file.endsWith(".md") || file.startsWith("dialects/")) continue;
  const text = fs.readFileSync(path.join(grammars, file), "utf8");
  if (!text.includes("```ebnf") && !text.includes("~~~ebnf")) continue;
  documents[file] = { hash: fnv1a64(text), dom: loader.readDocument(text, file) };
}
const compiled = { format: DOM_FORMAT, bootstrap: loader.bootstrapHash, documents };
write("grammars/compiled.json", JSON.stringify(compiled) + "\n");

// The grammar copies.
const copies = ["js/grammars", "python/src/gencmu/grammars", "go/grammars", "rust/grammars"]
  .filter((copy) => fs.existsSync(path.join(root, copy.split("/")[0])));
const sources = {};
for (const file of grammarFiles()) sources[file] = fs.readFileSync(path.join(grammars, file), "utf8");
sources["compiled.json"] = JSON.stringify(compiled) + "\n";
for (const copy of copies) {
  for (const [file, text] of Object.entries(sources)) write(`${copy}/${file}`, text);
}
write("dist/grammars.js", `// Generated by tools/sync.js from grammars/: every grammar document, by path.
(function (root) {
  "use strict";
  root.gencmuGrammars = ${JSON.stringify(sources)};
})(typeof self !== "undefined" ? self : this);
`);

// The browser bundle: the modules of js/src, except the Node entry point,
// in dependency order, inside one factory function with nothing outside it.
const sourceDirectory = path.join(root, "js", "src");
const modules = new Map();
for (const file of fs.readdirSync(sourceDirectory).filter((name) => name.endsWith(".js") && name !== "node.js")) {
  const text = fs.readFileSync(path.join(sourceDirectory, file), "utf8");
  const imports = [...text.matchAll(/^import\s[^;]*?from\s+"\.\/([^"]+)";$/gms)].map((match) => match[1]);
  modules.set(file, { text, imports });
}
const order = [];
const visit = (file, trail = []) => {
  if (order.includes(file)) return;
  if (trail.includes(file)) throw new Error(`an import cycle: ${[...trail, file].join(" → ")}`);
  for (const dependency of modules.get(file).imports) visit(dependency, [...trail, file]);
  order.push(file);
};
for (const file of [...modules.keys()].sort()) visit(file);
const declared = new Map();
const bodies = order.map((file) => {
  const body = modules.get(file).text
    .replace(/^import\s[^;]*?from\s+"[^"]+";$/gms, "")
    .replace(/^export\s+\{[^}]*\}\s+from\s+"[^"]+";$/gms, "")
    .replace(/^export\s+\*\s+from\s+"[^"]+";$/gm, "")
    .replace(/^export\s*\{\s*\};$/gm, "")
    .replace(/^export\s+(?=(async\s+)?(function|class|const|let)\b)/gm, "");
  for (const match of body.matchAll(/^(?:async\s+)?(?:function\*?|class|const|let)\s+([A-Za-z_$][\w$]*)/gm)) {
    if (declared.has(match[1])) throw new Error(`${match[1]} is declared in both ${declared.get(match[1])} and ${file}; the bundle needs unique top-level names`);
    declared.set(match[1], file);
  }
  return `  // ---- ${file}\n` + body.split("\n").map((line) => (line ? "  " + line : line)).join("\n");
});
const exported = [...fs.readFileSync(path.join(sourceDirectory, "index.js"), "utf8").matchAll(/export\s+(?:\{([^}]*)\}|function\s+(\w+)|const\s+(\w+))/g)]
  .flatMap((match) => (match[1] ? match[1].split(",").map((name) => name.trim()).filter(Boolean) : [match[2] || match[3]]));
const version = JSON.parse(fs.readFileSync(path.join(root, "js", "package.json"), "utf8")).version;
write("dist/gencmu.js", `// Generated by tools/sync.js from js/src/: the gencmu library as one factory
// function with nothing outside it, so that a page can hand its source to a
// worker built from a Blob, which fetches nothing.
(function (root) {
  "use strict";
  function gencmuFactory() {
${bodies.join("\n")}
    return { version: ${JSON.stringify(version)}, ${exported.join(", ")} };
  }
  root.gencmuFactory = gencmuFactory;
  root.gencmu = gencmuFactory();
})(typeof self !== "undefined" ? self : this);
`);

if (check && stale.length) {
  console.error(`out of date; run node tools/sync.js:\n  ${stale.join("\n  ")}`);
  process.exit(1);
}
console.log(check ? "generated files are up to date" : `wrote ${stale.length} file(s)`);
