#!/usr/bin/env node
// Regenerates every generated file from grammars/ and lib/js/src/, or, with
// --check, fails if any of them is out of date:
//
//   grammars/compiled.json   the DOM of every grammar document, keyed by hash
//   lib/js/grammars/         the npm package's copy of grammars/
//   dist/grammars.js         grammars/ as one object, for the browser
//   dist/gencmu.js           the library as one factory function, for the browser
//
// and the other packages' copies of grammars/ and of LICENSE under lib/. No
// dependencies; run it after editing a grammar.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Loader, fnv1a64 } from "../lib/js/src/node.js";
import { DOM_FORMAT } from "../lib/js/src/dom.js";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const grammars = path.join(root, "grammars");
const check = process.argv.includes("--check");
const stale = [];

function write(relative, content) {
  const file = path.join(root, relative);
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (current === content) return;
  stale.push(relative);
  if (!check) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
}

function grammarFiles(directory = grammars, prefix = "") {
  const files = [];
  // Hidden files, such as a desktop's .DS_Store, are not grammars.
  const entries = fs.readdirSync(directory, { withFileTypes: true }).filter((entry) => !entry.name.startsWith("."));
  for (const entry of entries.sort((a, b) => (a.name < b.name ? -1 : 1))) {
    const relative = prefix + entry.name;
    if (entry.isDirectory()) files.push(...grammarFiles(path.join(directory, entry.name), relative + "/"));
    else if (relative !== "compiled.json") files.push(relative);
  }
  return files;
}

// The bootstrap: the notation's own documents read with the bootstrap, until
// reading them again changes nothing (docs/design.md, "Self-hosting"). A
// change to the notation that the current bootstrap cannot read needs
// tools/write-bootstrap.js first.
const bootstrapPath = path.join(grammars, "notation", "bootstrap.json");
let bootstrapText = fs.readFileSync(bootstrapPath, "utf8");
// A loader of grammars/ with the given bootstrap and no precompiled DOMs.
/** @param {string} bootstrap */
const loaderWith = (bootstrap) => new Loader((relative) => {
  if (relative === "notation/bootstrap.json") return bootstrap;
  if (relative === "compiled.json") return undefined;
  const file = path.join(grammars, ...relative.split("/"));
  return fs.existsSync(file) ? fs.readFileSync(file, "utf8") : undefined;
});
for (let round = 0; ; round++) {
  const reader = loaderWith(bootstrapText);
  const current = JSON.parse(bootstrapText);
  const next = {
    format: DOM_FORMAT,
    stages: current.stages.map((stage) => ({
      name: stage.name,
      documents: stage.documents.map((document) => ({
        path: document.path,
        dom: reader.readDocument(fs.readFileSync(path.join(grammars, document.path), "utf8"), document.path),
      })),
    })),
  };
  const nextText = JSON.stringify(next) + "\n";
  if (nextText === bootstrapText) break;
  if (round === 3) throw new Error("the notation does not reach a fixpoint");
  bootstrapText = nextText;
}
write("grammars/notation/bootstrap.json", bootstrapText);

// The precompiled DOMs, read with the engine and the bootstrap.
const loader = loaderWith(bootstrapText);
const documents = {};
for (const file of grammarFiles()) {
  if (!file.endsWith(".md") || file.startsWith("dialects/")) continue;
  const text = fs.readFileSync(path.join(grammars, file), "utf8");
  if (!text.includes("```jbogenbau") && !text.includes("~~~jbogenbau")) continue;
  documents[file] = { hash: fnv1a64(text), dom: loader.readDocument(text, file) };
}
const compiled = { format: DOM_FORMAT, bootstrap: loader.bootstrapHash, documents };
write("grammars/compiled.json", JSON.stringify(compiled) + "\n");

// The licence, which every package ships beside its code.
const license = fs.readFileSync(path.join(root, "LICENSE"), "utf8");
for (const library of ["lib/js", "lib/python", "lib/go", "lib/rust"]) write(`${library}/LICENSE`, license);

// The grammar copies.
const copies = ["lib/js/grammars", "lib/python/src/gencmu/grammars", "lib/go/grammars", "lib/rust/grammars"];
const sources = {};
for (const file of grammarFiles()) sources[file] = fs.readFileSync(path.join(grammars, file), "utf8");
sources["compiled.json"] = JSON.stringify(compiled) + "\n";
for (const copy of copies) {
  for (const [file, text] of Object.entries(sources)) write(`${copy}/${file}`, text);
}
write("dist/grammars.js", `// Generated by tools/sync.js from grammars/: every grammar document, by path.
(function (root) {
  "use strict";
  root.gencmuGrammars = ${JSON.stringify(sources)};
})(typeof self !== "undefined" ? self : this);
`);

// The browser bundle: the modules of lib/js/src, except the Node entry point,
// in dependency order, inside one factory function with nothing outside it.
const sourceDirectory = path.join(root, "lib", "js", "src");
const modules = new Map();
for (const file of fs.readdirSync(sourceDirectory).filter((name) => name.endsWith(".js") && name !== "node.js")) {
  const text = fs.readFileSync(path.join(sourceDirectory, file), "utf8");
  const imports = [...text.matchAll(/^import\s[^;]*?from\s+"\.\/([^"]+)";$/gms)].map((match) => match[1]);
  modules.set(file, { text, imports });
}
const order = [];
const visit = (file, trail = []) => {
  if (order.includes(file)) return;
  if (trail.includes(file)) throw new Error(`an import cycle: ${[...trail, file].join(" → ")}`);
  for (const dependency of modules.get(file).imports) visit(dependency, [...trail, file]);
  order.push(file);
};
for (const file of [...modules.keys()].sort()) visit(file);
const declared = new Map();
const bodies = order.map((file) => {
  const body = modules.get(file).text
    .replace(/^import\s[^;]*?from\s+"[^"]+";$/gms, "")
    .replace(/^export\s+\{[^}]*\}\s+from\s+"[^"]+";$/gms, "")
    .replace(/^export\s+\*\s+from\s+"[^"]+";$/gm, "")
    .replace(/^export\s*\{\s*\};$/gm, "")
    .replace(/^export\s+(?=(async\s+)?(function|class|const|let)\b)/gm, "");
  for (const match of body.matchAll(/^(?:async\s+)?(?:function\*?|class|const|let)\s+([A-Za-z_$][\w$]*)/gm)) {
    if (declared.has(match[1])) throw new Error(`${match[1]} is declared in both ${declared.get(match[1])} and ${file}; the bundle needs unique top-level names`);
    declared.set(match[1], file);
  }
  return `  // ---- ${file}\n` + body.split("\n").map((line) => (line ? "  " + line : line)).join("\n");
});
const exported = [...fs.readFileSync(path.join(sourceDirectory, "index.js"), "utf8").matchAll(/export\s+(?:\{([^}]*)\}|function\s+(\w+)|const\s+(\w+))/g)]
  .flatMap((match) => (match[1] ? match[1].split(",").map((name) => name.trim()).filter(Boolean) : [match[2] || match[3]]));
const version = JSON.parse(fs.readFileSync(path.join(root, "lib", "js", "package.json"), "utf8")).version;
write("dist/gencmu.js", `// Generated by tools/sync.js from lib/js/src/: the gencmu library as one factory
// function with nothing outside it, so that a page can hand its source to a
// worker built from a Blob, which fetches nothing.
(function (root) {
  "use strict";
  function gencmuFactory() {
${bodies.join("\n")}
    return { version: ${JSON.stringify(version)}, ${exported.join(", ")} };
  }
  root.gencmuFactory = gencmuFactory;
  root.gencmu = gencmuFactory();
})(typeof self !== "undefined" ? self : this);
`);

if (check && stale.length) {
  console.error(`out of date; run node tools/sync.js:\n  ${stale.join("\n  ")}`);
  process.exit(1);
}
console.log(check ? "generated files are up to date" : `wrote ${stale.length} file(s)`);
